name: Sync main.py from Upstream

on:
  push:
    branches:
      - main
    paths:
      - 'sing-box-geosite/main.py'

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main

    - name: Sync main.py from upstream
      run: |
        git remote add upstream https://github.com/Toperlock/sing-box-geosite.git
        git fetch upstream
        git checkout upstream/main -- sing-box-geosite/main.py
        git add sing-box-geosite/main.py
        git commit -m "Sync main.py from upstream"
        git push origin main
